export default {
    APP_LOADED: 'APP_LOADED',
    TOOGLE_SIDEBAR: 'TOOGLE_SIDEBAR',
    TOOGLE_SEARCHBAR: 'TOOGLE_SEARCHBAR',
    ACTIVE_SIDEBARITEM: 'ACTIVE_SIDEBARITEM',
    CHANGE_SIDEBAR_WIDTH: 'CHANGE_SIDEBAR_WIDTH',

    FETCH_USER: 'FETCH_USER',
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',

    FETCH_USERS: 'FETCH_USERS',
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',

    FETCH_METRICS: 'FETCH_METRICS',
    FETCH_METRICS_SUCCESS: 'FETCH_METRICS_SUCCESS',
    FETCH_METRICS_FAILURE: 'FETCH_METRICS_FAILURE',

    FETCH_METRICS_COMPARE: 'FETCH_METRICS_COMPARE',
    FETCH_METRICS_COMPARE_SUCCESS: 'FETCH_METRICS_COMPARE_SUCCESS',
    FETCH_METRICS_COMPARE_FAILURE: 'FETCH_METRICS_COMPARE_FAILURE',
};
